---
- name: Create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    shell: /bin/bash
    append: yes

- name: Ensures Blackbox Exporter install and configuration directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
  with_items:
    - "{{ prometheus_blackbox_exporter_install_directory }}"
    - "{{ prometheus_blackbox_exporter_config_directory }}"

- name: Download Blackbox Exporter to install directory
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ prometheus_blackbox_exporter_version }}/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.{{ prometheus_platform }}.tar.gz"
    dest: "{{ prometheus_blackbox_exporter_install_directory }}"
    copy: no
    owner: "{{ prometheus_user }}"
  notify: restart blackbox_exporter

- name: Configure Blackbox Exporter
  template:
    src: blackbox.yml.j2
    dest: "{{ prometheus_blackbox_exporter_config_directory }}/blackbox.yml"
  notify: restart blackbox_exporter

- name: Add systemd Blackbox Exporter service
  template:
    src: blackbox_exporter.service.j2
    dest: /lib/systemd/system/blackbox_exporter.service
  notify: restart blackbox_exporter

- name: Enable and start Blackbox Exporter service
  systemd:
    name: blackbox_exporter
    state: started
    enabled: true
    daemon_reload: yes
